version: '2'
volumes:
 dbdata:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    container_name: crypto_django_container
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "5500:8000"
    depends_on:
      - db
