# Generated by Django 2.2.5 on 2020-12-21 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20201221_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='price',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 19, 31, 45, 580892), null=True),
        ),
        migrations.AlterField(
            model_name='cercademi',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 19, 31, 45, 583200), null=True),
        ),
        migrations.AlterField(
            model_name='criptomonedas',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 19, 31, 45, 578579), null=True),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 19, 31, 45, 582798), null=True),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 19, 31, 45, 579045), null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 19, 31, 45, 581655), null=True),
        ),
        migrations.AlterField(
            model_name='medidas',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 19, 31, 45, 580480), null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 19, 31, 45, 582080), null=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 21, 19, 31, 45, 581245), null=True),
        ),
    ]
