# Generated by Django 2.2.5 on 2021-10-08 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20210925_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cercademi',
            name='local',
        ),
        migrations.RemoveField(
            model_name='cercademi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='local',
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historialuser',
            name='criptomoneda',
        ),
        migrations.RemoveField(
            model_name='historialuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='local',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='medidas',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='local',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='categoria',
        ),
        migrations.AddField(
            model_name='criptomonedas',
            name='market_cap',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criptomonedas',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 4, 25, 40, 720104), null=True),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 4, 25, 40, 721146), null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 4, 25, 40, 723243), null=True),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cercademi',
        ),
        migrations.DeleteModel(
            name='Favoritos',
        ),
        migrations.DeleteModel(
            name='HistorialUser',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.DeleteModel(
            name='Medidas',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
