# Generated by Django 2.2.5 on 2021-10-08 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20211008_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='criptomonedas',
            name='circulating_supply',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criptomonedas',
            name='fully_diluted_market_cap',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criptomonedas',
            name='volume_24h',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criptomonedas',
            name='volume_24h_market_cap',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criptomonedas',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 4, 35, 18, 289958), null=True),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 4, 35, 18, 290903), null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 4, 35, 18, 292092), null=True),
        ),
    ]
