# Generated by Django 2.2.5 on 2021-10-08 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20211008_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptomonedas',
            name='circulating_supply',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criptomonedas',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 4, 50, 20, 537905), null=True),
        ),
        migrations.AlterField(
            model_name='criptomonedas',
            name='fully_diluted_market_cap',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criptomonedas',
            name='market_cap',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criptomonedas',
            name='volume_24h',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criptomonedas',
            name='volume_24h_market_cap',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 4, 50, 20, 539846), null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 8, 4, 50, 20, 541412), null=True),
        ),
    ]
