# Generated by Django 2.2.5 on 2021-10-10 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20211010_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptomonedas',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 10, 15, 57, 2, 620741), null=True),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 10, 15, 57, 2, 621969), null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 10, 15, 57, 2, 623419), null=True),
        ),
    ]
