# Generated by Django 2.2.5 on 2021-12-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '1735_auto_20211201_1949'),
        ('api', '1735_auto_20211201_1950'),
    ]

    operations = [
    ]
